const urlName = {
  '/dashboard': '主页',
  '/internal/list': '权限管理-账户管理-内部页面',
  '/external/list': '权限管理-账户管理-外部页面',
  '/role/internal/list': '权限管理-角色管理-内部页面',
  '/TradingPlatform/orderList': 'B2B交易管理-订单列表页面',
  '/TradingPlatform/List/ListDetail': 'B2B交易管理-订单详情页面',
  '/TradingPlatform/returnList': 'B2B交易管理-退货单列表页面',
  '/TradingPlatform/returnList/creditDetail': 'B2B交易管理-退货单详情页面',
  '/TradingPlatform/List/ListDetail/EditOrder': 'B2B交易管理-订单修改页面',
  '/ODS/DeliveryList': 'ODS管理-发货单列表页面',
  '/ODS/DeliveryList/DeliveryDetail': 'ODS管理-发货单详情页面',
  '/ODS/ReceiveList': 'ODS管理-收货单列表页面',
  '/ODS/ReceiveList/ReceiveDetail': 'ODS管理-收货单详情页面',
  '/jit/list': '财务管理-JIT财务报表页面',
  '/goods/list': '基础档案管理-货品列表页面',
  '/goods/detail': '基础档案管理-货品详情页面',
  '/stock/PhysicalSearch': '库存管理-实物库存查询页面',
  '/stock/PhysicalAllocation': '库存管理-实物库存管理页面',
  '/stock/ChannelAllocation': '库存管理-渠道库存管理页面',
  '/stock/ChannelAllocationB2C': '库存管理-渠道库存管理B2C页面',
  '/stock/ChannelAllocationBBC': '库存管理-渠道库存管理BBC页面',
  '/stock/ChannelAllocationJIT': '库存管理-渠道库存管理JIT页面',
  '/scm/list': '调拨管理-调拨申请单列表页面',
  '/scm/detail': '调拨管理-调拨申请单详情页面',
  '/scm/add': '调拨管理-调拨申请单新增页面',
  '/login': '登录页面',
  '/logout': '退出登录',
  '/OMS/OrderLisr': 'OMS-订单交易列表页面',
  '/OMS/OrderDetail': 'OMS-订单详情页面',
  '/OMS/ReceiveList': 'OMS-售后订单列表页面',
  '/OMS/ReceiveDetail': 'OMS-售后订单详情页面',
  '/Purchase/PurchaseList': '采购单据管理-采购单据列表',
  '/Purchase/AddPurchase': '采购单据管理-新增采购单',
  '/Purchase/PurchaseDetail': '采购单据管理-采购单据明细',
  '/purchase/download': '采购单据管理-采购单据明细下载'
}

export default urlName
